<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Array Operators / Arithmetic</Title>
    <Company>Jacobi Software</Company>
    <Description>Array and IEnumerable&lt;T&gt; extensions that allows arithmetic operations on arrays / collections.</Description>
    <Copyright>Copyright (c) 2025 Jacobi Software</Copyright>
    <Version>1.2.0</Version>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageTags>array-arithmetic</PackageTags>
    <PackageProjectUrl>https://github.com/obiwanjacobi/Jacobi.ArrayOperators</PackageProjectUrl>
    <RepositoryUrl>https://github.com/obiwanjacobi/Jacobi.ArrayOperators</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
